# Generated by Django 5.0 on 2023-12-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_talk', '0002_audiofile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AudioFile',
            new_name='Audio',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='file_audio',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='newstranscription',
            old_name='audofileObject',
            new_name='audioObject',
        ),
        migrations.RenameField(
            model_name='newstranscription',
            old_name='title',
            new_name='titlename',
        ),
        migrations.AlterField(
            model_name='news',
            name='audio_file',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
