# Generated by Django 5.0 on 2023-12-23 11:02

import music_talk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_talk', '0004_remove_newstranscription_newsobject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstranscription',
            name='titlename',
        ),
        migrations.AddField(
            model_name='newstranscription',
            name='title',
            field=models.CharField(default=1, max_length=240, verbose_name=music_talk.models.News),
            preserve_default=False,
        ),
    ]
