# Generated by Django 5.0 on 2023-12-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_talk', '0008_delete_mainnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(upload_to='audio2/'),
        ),
    ]
