# Generated by Django 5.0 on 2023-12-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_talk', '0009_alter_audio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstranscription',
            old_name='audioObject',
            new_name='audioObject_id',
        ),
    ]
