# Generated by Django 5.0 on 2023-12-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_talk', '0010_rename_audioobject_newstranscription_audioobject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='file',
        ),
        migrations.AddField(
            model_name='audio',
            name='last_file',
            field=models.FileField(default=1, upload_to='audio/'),
            preserve_default=False,
        ),
    ]
