# Generated by Django 5.0 on 2024-01-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_talk', '0011_remove_audio_file_audio_last_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('video_image', models.ImageField(upload_to='videosImages/')),
            ],
        ),
    ]
