# Generated by Django 5.0 on 2024-01-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_talk', '0012_mainvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='mail',
            field=models.EmailField(max_length=250),
        ),
    ]
