# Generated by Django 5.0 on 2024-01-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_talk', '0014_alter_subscriptions_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_subscribed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscriptions',
        ),
    ]
