# Generated by Django 5.0 on 2024-01-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_talk', '0015_subscriber_delete_subscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.TextField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
