# Generated by Django 5.0 on 2024-01-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_talk', '0017_contacts_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
