# Generated by Django 5.0 on 2024-01-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_talk', '0018_contacts_created_at_contacts_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='updated_at',
        ),
    ]
