# Generated by Django 5.0 on 2024-01-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_talk', '0019_remove_contacts_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newstranscription',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
